# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.FileField(null=True, upload_to='user', verbose_name='图片'),
        ),
    ]
